includes/functions/HandlePlanetQueue_TechnologySetNext.php
Fixes "invisible" tech queue progress when being on another planet than the main one (where "main one" is the planet conducting the research).
This bug would allow users to put lower level techs in the queue, which led to cheaper technological advancement.
Fixes https://github.com/mdziekon/UniEngine/issues/1
=> Fix Tech Queue bug

includes/functions/FleetControl_Retreat.php
Fixes #31 
TODO:
- The original bug was caused by the fact that the turning back script did not recognise "empty" united attacks (no joined fleets, just the main one) as United attacks, therefore not removing the ACS record from the database.
=> Remove the ACS row even if no fleets have joined

fleet.php
=> Fix fleet quick missions in non Pro-account mode

.eslintrc.json, composer.lock, package-lock.json, package.json
Closes #28 
- Upgraded JS dependencies:
- ``eslint``: ``5.11.0 -> 6.0.1``
- ``ansi-colors``: ``3.2.3 -> 4.0.1``
- ``del``: ``3.0.0 -> 4.1.1``
- ``gulp``: ``4.0.0 -> 4.0.2``
- ``gulp-terser``: ``1.1.6 -> 1.2.0``
- ``stylelint``: ``9.9.0 -> 10.1.0``
- ``terser``: ``3.13.1 -> 4.0.1``
- Upgraded PHP dependencies:
- ``google/recaptcha``: ``1.2.1 -> 1.2.2``
- ``phpmailer/phpmailer``: ``v6.0.6 -> v6.0.7``
- ``squizlabs/php_codesniffer``: ``3.3.2 -> 3.4.2``
=> Dependencies update (2019-06-30)

includes/debug.class.php, includes/functions.php
=> Morale system droptime calculation bugfix

common.php, includes/functions.php, includes/functions/CheckUserSessionCookie.php, install/index.php, login.php, logout.php, reg_ajax.php, settings.php
=> Session cookie key fix

includes/functions/LaboratoryPage.php, includes/functions/StructuresBuildingPage.php, includes/unlocalised.php, language/en/buildings.lang, language/pl/buildings.lang, modules/development/_includes.php, modules/development/components/ModernQueue/ModernQueue.component.php, modules/development/components/ModernQueue/index.php, modules/development/components/ModernQueue/row_element_firstel.tpl, modules/development/components/ModernQueue/row_element_nextel.tpl, modules/development/components/ModernQueue/row_infobox_generic.tpl, modules/development/components/index.php, modules/development/screens/ResearchListPage/ModernQueueLabUpgradeInfo/ModernQueueLabUpgradeInfo.component.php, modules/development/screens/ResearchListPage/ModernQueueLabUpgradeInfo/index.php, modules/development/screens/ResearchListPage/ModernQueueLabUpgradeInfo/row_infobox_otherplanetbox.tpl, modules/development/screens/ResearchListPage/ModernQueueLabUpgradeInfo/row_infobox_planetlink.tpl, modules/development/screens/ResearchListPage/ModernQueuePlanetInfo/ModernQueuePlanetInfo.component.php, modules/development/screens/ResearchListPage/ModernQueuePlanetInfo/index.php, modules/development/screens/ResearchListPage/ModernQueuePlanetInfo/row_infobox_researchplanet.tpl, modules/development/screens/ResearchListPage/index.php, modules/development/screens/index.php, templates/default_template/buildings_compact_queue_planetlink.tpl
=> Port minor fixes to the codebase from PR #61 | Part 7

includes/functions/BatimentBuildingPage.php, includes/functions/LaboratoryPage.php, includes/functions/ResearchBuildingPage.php, includes/functions/StructuresBuildingPage.php, includes/helpers/world/elements.common.functions.php, modules/development/_includes.php, modules/development/utils/index.php, modules/development/utils/queue.utils.php
=> Port minor fixes to the codebase from PR #61 | Part 9

language/en/buildings.lang, language/pl/buildings.lang, modules/development/components/LegacyQueue/LegacyQueue.component.php, modules/development/components/ModernQueue/ModernQueue.component.php
=> Port minor fixes to the codebase from PR #61 | Part 16

includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, includes/helpers/world/resources.functions.php, modules/flights/_includes.php, modules/flights/utils/calculations/calculateResourcesLoss.utils.UETest.php, modules/flights/utils/calculations/calculateResourcesLoss.utils.php, modules/flights/utils/calculations/index.php
Currently there are three places with resources loss and debris calculation code duplicated. All of them should use a shared function to calculate these values.
- #91
=> Refactor fleet missions' code | Part 02 | Resources loss & debris calculation

includes/functions/FlyingFleetHandler.php, includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, modules/flights/_includes.php, modules/flights/utils/fleetCache/index.php, modules/flights/utils/fleetCache/updateGalaxyDebris.utils.php
Currently there are three places with galaxy entry debris update code duplicated. All of them should use a shared function to update the entry.
- #91
=> Refactor fleet missions' code | Part 02 | Galaxy debris update

includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, modules/flights/_includes.php, modules/flights/utils/calculations/calculatePillageFactor.utils.php, modules/flights/utils/modifiers/calculateMoraleModifiers.utils.php, modules/flights/utils/modifiers/index.php
Currently there are several places where morale-related modifiers are calculated manually for each attacker and defender, also duplicated in several files. All of these modifiers are applied identically, therefore they should be calculated using a shared utility function.
- #91
=> Refactor fleet missions' code | Part 04 | Morale modifiers calculation

includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, includes/vars_elementcategories.php, modules/flights/_includes.php, modules/flights/utils/initializers/index.php, modules/flights/utils/initializers/technologies.utils.php
Currently there are several places where user technologies are prepared for combat calculation. All of that duplication should be merged into one shared utility.
- #91
=> Refactor fleet missions' code | Part 05 | User technologies initialization

includes/functions/FlyingFleetHandler.php, includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseExpedition.php, includes/functions/MissionCaseGroupAttack.php, includes/functions/MissionCaseMIP.php, includes/functions/MissionCaseSpy.php, includes/helpers/world/elements.common.functions.php, modules/flights/_includes.php, modules/flights/utils/calculations/calculateResourcesLoss.utils.php, modules/flights/utils/fleetCache/updateUserStats.utils.php, modules/flights/utils/initializers/userStats.utils.php
Currently there are several places where combat statistics (units destroyed & lost) are being parsed and stored in objects. What is more, some of the operations use internal structure keys, which should be hidden by some sort of abstraction when incrementing the structure. All of that duplication should be merged into shared utilities and abstracted away where needed.
- #91
=> Refactor fleet missions' code | Part 06 | User stats aggregation

includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, includes/helpers/fleets/functions.php, modules/flights/_includes.php, modules/flights/utils/calculations/calculatePillageStorage.utils.UETest.php, modules/flights/utils/calculations/calculatePillageStorage.utils.php, modules/flights/utils/factories/createFleetDevelopmentLogEntries.utils.php, modules/flights/utils/factories/createFleetUpdateEntry.utils.php, modules/flights/utils/factories/index.php
Certain actions like pillage storage capacity calculation, fleet row updates aggregation & development log updates aggregation are all common to all three types of attacks (Solo, United, Destruction), however they all have these actions duplicated in the code. These things should all be shared, one way or the other.
- #91
=> Refactor fleet missions' code | Part 07 | Post-combat fleet updates

includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, includes/helpers/common/collections.functions.php, includes/helpers/common/navigation.functions.php, modules/flights/_includes.php, modules/flights/utils/factories/createCombatMessages.utils.php, modules/flights/utils/helpers/hasLostAnyDefenseSystem.utils.php, modules/flights/utils/helpers/index.php
Certain actions like pillage storage capacity calculation, fleet row updates aggregation & development log updates aggregation are all common to all three types of attacks (Solo, United, Destruction), however they all have these actions duplicated in the code. These things should all be shared, one way or the other.
- The answer is `NO`, this counter represents the losses in combat. Including fleet destruction "by the moon" would obscure that, so for now let's leave it be.
- The answer is `NO`, there should be no debris field created when the fleet gets destroyed "by the moon".
- #91
=> Refactor fleet missions' code | Part 07 | Post-combat system messages

includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, includes/helpers/common/collections.functions.php, modules/flights/_includes.php, modules/flights/utils/calculations/calculateUnitsRebuild.utils.php
When calculating the result of an attack, all three missions (attack, destruction & group attack) have separate, hardcoded implementation of defender's defense systems rebuilding. This should be moved to a shared utility to prevent code duplication & unify their behaviour (especially since there's a difference right now, looks like a simple miss type from the old days).
- #91
=> Refactor fleet missions' code | Part 09 | Defense systems rebuild

includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, modules/flights/_includes.php, modules/flights/utils/initializers/defenderDetails.utils.php
All three possible combat missions (MissionAttack, MissionDestruction & MissionGroupAttack) share the same mechanism of defenders' details initialisation and aggregation. This mechanism should be implemented in just one place and shared among them.
- #91
=> Refactor fleet missions' code | Part 10 | Defenders' details aggregation

includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, modules/flights/utils/fleetCache/updateUserStats.utils.php
All three possible combat missions (MissionAttack, MissionDestruction & MissionGroupAttack) share the same mechanism of combat result stats aggregation (whether the fight was won, drawn or lost). This mechanism should be implemented in just one place and shared among them.
- #91
=> Refactor fleet missions' code | Part 11 | Combat result stats aggregation

includes/functions/MissionCaseAttack.php, includes/functions/MissionCaseDestruction.php, includes/functions/MissionCaseGroupAttack.php, modules/flights/_includes.php, modules/flights/utils/calculations/calculatePostCombatMorale.utils.php, modules/flights/utils/calculations/calculatePostCombatMoraleUpdates.utils.php, modules/flights/utils/factories/createCombatReportMoraleEntry.utils.php, modules/flights/utils/fleetCache/morale.utils.php
All three possible combat missions (MissionAttack, MissionDestruction & MissionGroupAttack) share almost the same mechanism of combat morale updating. This mechanism should be implemented in just one place and shared among them.
- #91
=> Refactor fleet missions' code | Part 12 | Combat morale updates

language/en/tasks.lang
579&580 should have said storage in my opinion
748 was polish, I believe its supposed to say united attacks
=> Fixed 2 translation errors in the english tasks.lang file

includes/functions.php
Relates to #112 
Fixes the issue with tasks completion when we're updating more than one player's task data at a time.
Changelog:
=> GH-112 | Fix tasks data handling upon completion

messages.php, modules/messages/_includes.php, modules/messages/input/sendMessage.userCommands.php, modules/messages/utils/createReplyMessageSubject.utils.php, modules/messages/utils/fetchFormDataForReply.utils.php, modules/messages/utils/fetchRecipientDataByUserId.utils.php, modules/messages/utils/fetchRecipientDataByUsername.utils.php, modules/messages/utils/getMessageCopyId.utils.php, modules/messages/utils/normalizeFormData.utils.php, modules/messages/utils/sendMessage.utils.php, modules/messages/validators/index.php, modules/messages/validators/validateWithIgnoreSystem.validators.php
`messages.php` is a huge file that needs to be split into smaller chunks to make it more manageable and flexible.
- #126
=> Refactor messages sending form

includes/CombatEngineAres.php, includes/ares/calculations.php, includes/ares/distributions.php, includes/ares/evaluators.php, includes/ares/index.php, includes/ares/initializers.php
`CombatEngineAres.php` is a huge pile of duplicated code all over the place. It's time to extract repeated pieces into reusable functionalities to improve readability (and future modifications), reduce complexity and accidental inconsistencies between attackers' & defenders' ships behaviour.
- #131
=> Refactor Battle Engine (part 1)

includes/CombatEngineAres.php, includes/ares/calculations.php
`CombatEngineAres.php` is a huge pile of duplicated code all over the place. It's time to extract repeated pieces into reusable functionalities to improve readability (and future modifications), reduce complexity and accidental inconsistencies between attackers' & defenders' ships behaviour.
- #131
=> Refactor Battle Engine (part 3)

fleet1.php, fleet2.php, fleet3.php, language/en/fleet.lang, language/pl/fleet.lang, modules/flightControl/_includes.php, modules/flightControl/index.php, modules/flightControl/utils/index.php, modules/flightControl/utils/validators/fleetArray.validator.php, modules/flightControl/utils/validators/index.php
`fleet*.php` files are a huge pile of duplicated code. It's time to extract repeated pieces into reusable functionalities to improve readability (and future modifications), reduce complexity and accidental inconsistencies between subsequent steps.
- #139
=> Flight Control refactor (part 01) - Fleet array validation

admin/user_info.php, admin/userlist.php, ajax/galaxyfleet.php, ajax/sendmissiles.php, fleet.php, fleet1.php, fleet2.php, fleet3.php, galaxy.php, includes/functions/GalaxyRowUser.php, language/en/fleet.lang, language/pl/fleet.lang, modules/flightControl/_includes.php, modules/flightControl/utils/factories/createFleetDevLogEntry.factory.php, modules/flightControl/utils/fetchers/fetchPlanetOwnerDetails.fetcher.php, modules/flightControl/utils/fetchers/index.php, modules/flightControl/utils/helpers/getAvailableHoldTimes.helper.php, modules/flightControl/utils/helpers/getAvailableSpeeds.helper.php, modules/flightControl/utils/helpers/getFleetUnionJoinData.helper.php, modules/flightControl/utils/helpers/getFleetsInFlightCounters.helper.php, modules/flightControl/utils/helpers/getUserExpeditionSlotsCount.helper.php, modules/flightControl/utils/helpers/getUserFleetSlotsCount.helper.php, modules/flightControl/utils/helpers/getValidMissionTypes.helper.php, modules/flightControl/utils/helpers/index.php, modules/flightControl/utils/validators/joinUnion.validator.php, modules/flightControl/utils/validators/missionHold.validator.php, overview.php, templates/default_template/fleet2_body.tpl
`fleet*.php` files are a huge pile of duplicated code. It's time to extract repeated pieces into reusable functionalities to improve readability (and future modifications), reduce complexity and accidental inconsistencies between subsequent steps.
- #139
=>  Flight Control refactor (part 02) - Various refactors

includes/db.php, includes/unlocalised.php, modules/registration/_includes.php, modules/registration/utils/cookies.utils.php, modules/registration/utils/galaxy.utils.php, modules/registration/utils/general.utils.php, modules/registration/utils/queries.utils.php, modules/registration/validators/index.php, modules/registration/validators/validateReCaptcha.validators.php, modules/registration/validators/validateTakenParams.validators.php, reg_ajax.php
Relates to #150 (code cleanup for further sessions refactor)
Changelog:
=> Registration cleanup (part 2)

modules/registration/_includes.php, modules/registration/input/index.php, modules/registration/input/normalization.input.php, modules/registration/utils/queries.utils.php, modules/registration/validators/validateInputs.validators.php, reg_ajax.php
Relates to #150 (code cleanup for further sessions refactor)
Changelog:
=> Registration cleanup (part 3)

common.php, includes/per_module/common/userdata_helpers.php, language/en/common_activationlock.lang, language/en/system.lang, language/fr/common_activationlock.lang, language/pl/common_activationlock.lang, language/pl/system.lang, logout.php, templates/default_template/common_activationlock.tpl
=> Allow to logout when account is locked because activation has not been completed

ajax/sendmissiles.php, fleet3.php, modules/flightControl/_includes.php, modules/flightControl/utils/errors/noobProtection.utils.php, modules/flightControl/utils/validators/noobProtection.validator.php
=> Refactor fleet missions' code | Part 18 | Noob protection validator

ajax/sendmissiles.php, includes/functions/GalaxyRowActions.php, includes/functions/GalaxyRowDebris.php, includes/functions/GalaxyRowMoon.php, includes/functions/GalaxyRowPlanet.php, includes/functions/GalaxyRowPlanetName.php, includes/functions/ShowGalaxyRows.php, includes/helpers/_includes.php, includes/helpers/world/checks.functions.UETest.php, includes/helpers/world/checks.functions.php, phalanx.php
=> GH-208 | Refactor galaxy rendering | Assorted refactors (#01)

ajax/galaxyfleet.php, fleet1.php, fleet2.php, fleet3.php, includes/helpers/fleets/functions.php, includes/unlocalised.php, modules/flightControl/_includes.php, modules/flightControl/screens/SendWizardStepTwo/components/SpeedSelector/SpeedSelector.component.php, modules/flightControl/screens/SendWizardStepTwo/components/SpeedSelector/index.php, modules/flightControl/screens/SendWizardStepTwo/components/SpeedSelector/optionBody.tpl, modules/flightControl/screens/SendWizardStepTwo/components/SpeedSelector/optionsSeparator.tpl, modules/flightControl/screens/SendWizardStepTwo/components/index.php, modules/flightControl/screens/SendWizardStepTwo/index.php, modules/flightControl/utils/errors/tryJoinUnion.utils.php, modules/flightControl/utils/fetchers/fetchJoinableUnionFlights.fetcher.php, modules/flightControl/utils/helpers/getSlowestShipSpeed.helper.php, modules/flightControl/utils/helpers/tryJoinUnion.helper.php, modules/flights/utils/checks/isValidCoordinate.checks.php, templates/default_template/fleet1_body.tpl
=> GH-139 | Refactor flight control | Fleet sending (assorted refactors #07)

language/en/overview.lang, language/pl/overview.lang, modules/overview/_includes.php, modules/overview/screens/Overview/components/AdminAlerts/AdminAlerts.component.php, modules/overview/screens/Overview/components/AdminAlerts/body.tpl, modules/overview/screens/Overview/components/AdminAlerts/index.php, modules/overview/screens/Overview/components/EmailChangeInfo/EmailChangeInfo.component.php, modules/overview/screens/Overview/components/EmailChangeInfo/body.tpl, modules/overview/screens/Overview/components/EmailChangeInfo/index.php, modules/overview/screens/Overview/components/NewMessagesInfo/NewMessagesInfo.component.php, modules/overview/screens/Overview/components/NewMessagesInfo/body.tpl, modules/overview/screens/Overview/components/NewMessagesInfo/index.php, modules/overview/screens/Overview/components/NewSurveysInfo/NewSurveysInfo.component.php, modules/overview/screens/Overview/components/NewSurveysInfo/body.tpl, modules/overview/screens/Overview/components/NewSurveysInfo/index.php, overview.php, templates/default_template/overview_body.tpl
Overview screen has a lot of components that should have their own (sub)modules, let's refactor this.
#230
=> GH-230 | Overview - Alert components (part 1)
