includes/functions.php
``isPro()`` should not be always ``true``.
=> Fix isPro() function

lostcode.php
=> Fix the "main page" link on the Lost code page

README.md, docs/articles/defining-custom-terms-of-service.md, docs/index.md, language/en/rules.definitions.default.lang, language/pl/rules.definitions.default.lang, reg_mainpage.php, rules.php
Follow-up of #27 
- ReCaptcha injector now respects the language set in the cookie
- Make rules definition format a bit more consistent when handling nesting
- Document custom Terms of Service definition
=> English translation | follow-up #1

includes/helpers/_includes.php, includes/helpers/common/navigation.php, index.php
=> Minor index page refactor

includes/functions/AddBuildingToQueue.php, includes/functions/BatimentBuildingPage.php, includes/functions/CancelBuildingFromQueue.php, includes/functions/RemoveBuildingFromQueue.php, includes/functions/StructuresBuildingPage.php, includes/helpers/_includes.php, includes/helpers/planets/structures.queues.functions.php, includes/helpers/users/functions.php
=> Port minor fixes to the codebase from PR #61 | Part 3

includes/functions/LaboratoryPage.php, includes/functions/ResearchBuildingPage.php, includes/functions/TechQueue_Add.php, includes/functions/TechQueue_Remove.php, includes/functions/TechQueue_RemoveQueued.php, includes/helpers/_includes.php, includes/helpers/planets/functions.php, includes/helpers/planets/research.queues.functions.php, includes/helpers/users/functions.php
=> Port minor fixes to the codebase from PR #61 | Part 4

buildings.php, includes/functions/AddBuildingToQueue.php, includes/functions/BatimentBuildingPage.php, includes/functions/CancelBuildingFromQueue.php, includes/functions/LaboratoryPage.php, includes/functions/RemoveBuildingFromQueue.php, includes/functions/ResearchBuildingPage.php, includes/functions/StructuresBuildingPage.php, includes/functions/TechQueue_Add.php, includes/functions/TechQueue_Remove.php, includes/functions/TechQueue_RemoveQueued.php, includes/helpers/_includes.php, includes/helpers/planets/elements.functions.php, includes/helpers/uni/functions.php, modules/development/_includes.php, modules/development/index.php, modules/development/input/index.php, modules/development/input/research.userCommands.php, modules/development/input/structures.userCommands.php
=> Port minor fixes to the codebase from PR #61 | Part 5

includes/functions/StructuresBuildingPage.php
=> Port minor fixes to the codebase from PR #61 | Part 12

includes/functions/LaboratoryPage.php
=> Port minor fixes to the codebase from PR #61 | Part 13

includes/functions/LaboratoryPage.php, includes/functions/ShipyardPage.php, includes/functions/StructuresBuildingPage.php, modules/development/_includes.php, modules/development/components/GridViewElementIcon/GridViewElementIcon.component.php, modules/development/components/GridViewElementIcon/addon_countable_inputs.tpl, modules/development/components/GridViewElementIcon/body.tpl, modules/development/components/GridViewElementIcon/disable_overlay.tpl, modules/development/components/GridViewElementIcon/index.php, modules/development/components/GridViewElementIcon/level_modifier.tpl, templates/default_template/buildings_compact_list_element_lab.tpl, templates/default_template/buildings_compact_list_element_structures.tpl, templates/default_template/buildings_compact_list_levelmodif.tpl
=> Port minor fixes to the codebase from PR #61 | Part 14

buildings.php, includes/functions/BatimentBuildingPage.php, includes/functions/LaboratoryPage.php, includes/functions/ResearchBuildingPage.php, includes/functions/StructuresBuildingPage.php, includes/helpers/common/collections.functions.php, includes/helpers/world/elements.common.functions.php, modules/development/_includes.php, modules/development/utils/structures.utils.php
=> Port minor fixes to the codebase from PR #61 | Part 16

language/en/lostpassword.lang, language/pl/lostpassword.lang
Thank you for your comments on the previous PR. Here is a new one.
=> Updating lostpassword language files

includes/CombatEngineAres.php
`CombatEngineAres.php` is a huge pile of duplicated code all over the place. It's time to extract repeated pieces into reusable functionalities to improve readability (and future modifications), reduce complexity and accidental inconsistencies between attackers' & defenders' ships behaviour.
- #131
=> Refactor Battle Engine (part 2)

ajax/galaxyfleet.php, ajax/sendmissiles.php, fleet3.php, modules/flightControl/_includes.php, modules/flightControl/utils/factories/createAlertFiltersSearchParams.factory.php, modules/flightControl/utils/fetchers/fetchActiveSmartFleetsBlockadeEntries.fetcher.php, modules/flightControl/utils/validators/smartFleetsBlockadeState.validator.php
`fleet*.php` files are a huge pile of duplicated code. It's time to extract repeated pieces into reusable functionalities to improve readability (and future modifications), reduce complexity and accidental inconsistencies between subsequent steps.
- #139
=> Flight Control refactor (part 03) - Alerts & Smart Fleets Blockade refactor

README.md, includes/functions/CheckUserSessionCookie.php, includes/helpers/users/session.functions.php, language/en/login.lang, language/fr/login.lang, language/pl/login.lang, login.php, lostpassword.php, modules/session/_includes.php, modules/session/index.php, modules/session/input/cookieLogin.inputHandler.php, modules/session/input/index.php, modules/session/input/language.inputHandler.php, modules/session/input/localIdentityLogin.inputHandler.php, modules/session/screens/LoginView/LoginView.component.php, modules/session/screens/LoginView/components/LoginForm/LoginForm.component.php, modules/session/screens/LoginView/components/LoginForm/form_body.tpl, modules/session/screens/LoginView/components/LoginForm/index.php, modules/session/screens/LoginView/components/index.php, modules/session/screens/LoginView/index.php, modules/session/screens/index.php, modules/session/utils/cookie.utils.php, modules/session/utils/index.php, modules/session/utils/localIdentityV1.utils.php, modules/session/utils/rateLimiter.utils.php, modules/session/utils/redirects.utils.php, overview.php, reg_ajax.php, settings.php
=> Session handling improvements (part 1)

includes/db.php, includes/helpers/users/session.functions.php, includes/unlocalised.php, language/en/reg_ajax.lang, language/pl/reg_ajax.lang, modules/registration/_includes.php, modules/registration/components/RegistrationConfirmationMail/RegistrationConfirmationMail.component.php, modules/registration/components/RegistrationConfirmationMail/body.tpl, modules/registration/components/RegistrationConfirmationMail/index.php, modules/registration/components/index.php, modules/registration/index.php, modules/registration/utils/cookies.utils.php, modules/registration/utils/index.php, modules/registration/utils/queries.utils.php, reg_ajax.php
Relates to #150 (code cleanup for further sessions refactor)
Changelog:
=> Registration cleanup (part 1)

composer.json, composer.lock
Relates to #166 #161
Changelog:
=> PHP Deps update (2022-03)

modules/registration/_includes.php, modules/registration/utils/errors.utils.php, reg_ajax.php
Relates to #150 (code cleanup for further sessions refactor)
Changelog:
=> Registration cleanup (part 4)

includes/unlocalised.php, simulator.php
=> Refactor fleet missions' code | Part 15 | Simulator should use Attack utils

modules/flightControl/utils/errors/fleetArray.utils.php, modules/flightControl/utils/errors/joinUnion.utils.php
Fixes regression caused by #183 by adding missing files
- #91
=> Refactor fleet missions' code | Part 16a | Add missing files to repo

fleet3.php, language/en/fleet.lang, language/pl/fleet.lang, modules/flightControl/_includes.php, modules/flightControl/utils/errors/bashLimit.utils.php, modules/flightControl/utils/fetchers/fetchBashValidatorFlightLogEntries.fetcher.php, modules/flightControl/utils/validators/bashLimit.validator.php
...
- Regression since https://github.com/mdziekon/UniEngine/pull/46
- #91
=> Refactor fleet missions' code | Part 17 | Bash limits validator

ajax/galaxyfleet.php, ajax/sendmissiles.php, fleet2.php, fleet3.php, modules/flightControl/_includes.php, modules/flightControl/utils/factories/createAlertFiltersSearchParams.factory.php, modules/flightControl/utils/fetchers/fetchPlanetOwnerDetails.fetcher.php, modules/flightControl/utils/fetchers/fetchTargetGalaxyDetails.fetcher.php, modules/flightControl/utils/helpers/getTargetInfo.helper.php, modules/flightControl/utils/updaters/fleetArchiveEntryPersist.updaters.php, modules/flightControl/utils/updaters/fleetPersist.updaters.php
=>  Refactor fleet missions' code | Part 20 | Target info getter refactor

fleet.php, fleetretreat.php, modules/flightControl/_includes.php, modules/flightControl/components/RetreatInfoBox/RetreatInfoBox.component.php, modules/flightControl/components/RetreatInfoBox/body.tpl, modules/flightControl/components/RetreatInfoBox/index.php, modules/flightControl/components/index.php, modules/flightControl/enums/RetreatResultType.enum.php, modules/flightControl/enums/index.php, templates/default_template/fleet_body.tpl
=> GH-139 | Refactor flight control | Retreating refactor

fleet.php, fleet1.php, fleet2.php, modules/flightControl/_includes.php, modules/flightControl/components/SmartFleetBlockadeInfoBox/SmartFleetBlockadeInfoBox.component.php, modules/flightControl/components/SmartFleetBlockadeInfoBox/SmartFleetBlockadeInfoBox.utils.php, modules/flightControl/components/SmartFleetBlockadeInfoBox/index.php, overview.php
=> GH-139 | Refactor flight control | Smart Fleet Blockade infobox

fleet1.php, language/en/fleet.lang, language/pl/fleet.lang, modules/flightControl/_includes.php, modules/flightControl/components/TargetsSelector/TargetsSelector.component.php, modules/flightControl/components/TargetsSelector/body.tpl, modules/flightControl/components/TargetsSelector/index.php, modules/flightControl/utils/fetchers/fetchSavedShortcuts.fetcher.php
=> GH-139 | Refactor flight control | Shortcuts displaying

ajax/galaxyfleet.php, fleet.php, fleet2.php, fleet3.php, modules/flightControl/components/UnionManagement/UnionManagement.component.php, modules/flightControl/screens/Shortcuts/commands/upsertShortcut.command.php, modules/flights/_includes.php, modules/flights/utils/calculations/calculateUnionFlightTimeDiff.utils.php, modules/flights/utils/checks/index.php, modules/flights/utils/checks/isValidCoordinate.checks.php, phalanx.php
...
- (regression (?) of #199) 
- #139
=> GH-139 | Refactor flight control | Fleet sending (assorted refactors #01)

fleet3.php, includes/helpers/common/collections.functions.php, includes/unlocalised.php, modules/flightControl/_includes.php, modules/flightControl/utils/checks/hasMetPushAlertConditions.checks.php, modules/flightControl/utils/checks/index.php, modules/flightControl/utils/factories/createMultiAlert.factory.php, modules/flightControl/utils/factories/createPushAlert.factory.php, modules/flightControl/utils/fetchers/fetchMultiDeclaration.fetcher.php, modules/flightControl/utils/fetchers/fetchUsersWithMatchingIp.fetcher.php
=>  GH-139 | Refactor flight control | Alerts refactor

fleet3.php, modules/flightControl/_includes.php, modules/flightControl/utils/helpers/extractUnionFleetIds.helper.php, modules/flightControl/utils/updaters/fleetArchiveACSEntries.updaters.php, modules/flightControl/utils/updaters/updateFleetOriginPlanet.updaters.php, modules/flightControl/utils/updaters/updateUnionEntry.updaters.php, modules/flightControl/utils/updaters/updateUnionFleets.updaters.php
=> GH-139 | Refactor flight control | Fleet sending (assorted refactors #02)

ajax/galaxyfleet.php, ajax/sendmissiles.php, fleet3.php, includes/functions.php, modules/flightControl/_includes.php, modules/flightControl/utils/checks/hasMetPushAlertConditions.checks.php, modules/flightControl/utils/errors/fleetResources.utils.php, modules/flightControl/utils/errors/flightSlots.utils.php, modules/flightControl/utils/errors/targetOwner.utils.php, modules/flightControl/utils/factories/createFleetUsersStatsData.factory.php, modules/flightControl/utils/factories/createPushAlert.factory.php, modules/flightControl/utils/helpers/noobProtection.helper.php, modules/flightControl/utils/inputs/normalizeFleetResources.inputs.php, modules/flightControl/utils/validators/fleetResources.validator.php, modules/flightControl/utils/validators/flightSlots.validator.php, modules/flightControl/utils/validators/noobProtection.validator.php, modules/flightControl/utils/validators/targetOwner.validator.php
=> GH-139 | Refactor flight control | Fleet sending (assorted refactors #03)

ajax/galaxyfleet.php, ajax/sendmissiles.php, fleet2.php, fleet3.php, includes/functions/GalaxyRowUser.php, includes/helpers/uni/functions.php, language/en/fleet.lang, language/pl/fleet.lang, modules/flightControl/_includes.php, modules/flightControl/utils/helpers/getAvailableExpeditionTimes.helper.php, modules/flightControl/utils/validators/missionExpedition.validator.php, modules/flightControl/utils/validators/noobProtection.validator.php, templates/default_template/fleet2_body.tpl
=> GH-139 | Refactor flight control | Fleet sending (Stay time improvements)

includes/functions/GalaxyRowActions.php, includes/functions/GalaxyRowAlly.php, includes/functions/GalaxyRowDebris.php, includes/functions/GalaxyRowMoon.php, includes/functions/GalaxyRowPlanet.php, includes/functions/GalaxyRowPlanetName.php, includes/functions/GalaxyRowUser.php, includes/functions/ShowGalaxyRows.php
=> GH-208 | Refactor galaxy rendering | Code flattening

fleet1.php, fleet2.php, fleet3.php, modules/flightControl/_includes.php, modules/flightControl/utils/errors/fleetArray.utils.php, modules/flightControl/utils/helpers/getFleetArrayInfo.helper.php, modules/flightControl/utils/validators/fleetArray.validator.php
=> GH-139 | Refactor flight control | Fleet sending (assorted refactors #06)

includes/helpers/_includes.php, includes/helpers/world/enums/PlanetType.enum.php, includes/helpers/world/enums/index.php, modules/phalanx/_includes.php, modules/phalanx/index.php, modules/phalanx/screens/PlanetScan/PlanetScan.screen.php, modules/phalanx/screens/PlanetScan/components/PlanetScanResult/PlanetScanResult.component.php, modules/phalanx/screens/PlanetScan/components/PlanetScanResult/body.tpl, modules/phalanx/screens/PlanetScan/components/PlanetScanResult/index.php, modules/phalanx/screens/PlanetScan/components/index.php, modules/phalanx/screens/PlanetScan/index.php, modules/phalanx/screens/index.php, modules/phalanx/utils/effects/index.php, modules/phalanx/utils/effects/updateMoonFuelOnUsage.effect.php, modules/phalanx/utils/errors/index.php, modules/phalanx/utils/errors/tryScanPlanet.errors.php, modules/phalanx/utils/helpers/canUserBypassChecks.helper.php, modules/phalanx/utils/helpers/index.php, modules/phalanx/utils/helpers/tryScanPlanet.helper.php, modules/phalanx/utils/index.php, modules/phalanx/utils/queries/getTargetDetails.query.php, modules/phalanx/utils/queries/index.php, modules/phalanx/utils/queries/updatePhalanxMoon.query.php, phalanx.php
=> GH-221 | Refactor Phalanx screen

language/en/system.lang, language/pl/system.lang, modules/settings/utils/errorMappers/tryDeleteUserIgnoreEntries.errorMapper.php, modules/settings/utils/errorMappers/tryEnableVacation.errorMapper.php, modules/settings/utils/errorMappers/tryIgnoreUser.errorMapper.php, modules/settings/utils/errorMappers/validateEmailChange.errorMapper.php, modules/settings/utils/errorMappers/validatePasswordChange.errorMapper.php, modules/settings/utils/errorMappers/validateUsernameChange.errorMapper.php
Fixes minor bug introduced in #225, where generic error would have no message content, because it was using an error message from a lang file which is not imported.
=> GH-224 | Fix "unknown error" message in Settings
